### ISSUE TITLE
Name of the repository

### ISSUE THREAD

**Issue by jcchavezs** [3schwartz/openfga-operator#19]
I suggest the name of the repository changes into `openfga-operator` as there is another repository associated to FGA https://github.com/Fate-Grand-Automata/FGA

**Comment by 3schwartz** [comment]
Hi @jcchavezs 

Seems like OpenFGA is a trademark. Do you know what the rules are regarding using the name?🤔

**Comment by aaguiarz** [comment]
Hi @3schwartz 

Details are here https://www.linuxfoundation.org/legal/trademark-usage. 

There are several repositories that are not in the OpenFGA organization using openfga in its name.

IMHO, I don't feel strongly about the need to rename it, the are other projects related to OpenFGA that use `fga` in their name, and even the OpenFGA CLI is called `fga` :)

It would make it easier to find if you are searching repositories related to "openfga"

**Comment by 3schwartz** [comment]
Thanks for the reply, @aaguiarz.

I use `fga-operator` throughout the code (namespaces, charts, etc.), and changing everything to match the repository name would be a large and breaking refactor.

I’ll likely just rename the repository to `openfga-operator` and accept the inconsistency with the codebase for now 🤔

**Comment by 3schwartz** [comment]
Renamed and kept `fga-operator` throughout the code (namespaces, charts, etc.).

**Comment by 3schwartz** [comment]
Unfortunately needed to change back since path to `index.yaml` was broken. Got `failed to fetch https://3schwartz.github.io/fga-operator/index.yaml : 404 Not Found`.

Since I don’t want to change chart name now (or CRD) I will change it back.
